require('dotenv').config();
const db = require('../models');

const seed = async () => {
  try {
    console.log('🔄 Baza bilan ulanish tekshirilmoqda...');
    await db.sequelize.authenticate();
    console.log('✅ PostgreSQL ulanishi muvaffaqiyatli.');

    console.log('🔄 Jadvallar tozalash va yaratish (force sync)...');
    await db.sequelize.sync({ force: true });
    console.log('✅ Jadvallar yaratildi.');

    // 1. Asosiy Klinika (Multi-tenant Tenant 1)
    const clinic = await db.Clinic.create({
      name: 'DentUz Markaziy Klinika',
      address: 'Toshkent sh., Amir Temur shox ko\'chasi 15-uy',
      phone: '+998 71 200 00 00',
      workingHours: '09:00 - 20:00',
      subscriptionPlan: 'pro',
    });
    console.log(`✅ Klinika yaratildi: ${clinic.name}`);

    // 2. Foydalanuvchilar (Xodimlar)
    const usersData = [
      {
        name: 'Dr. Jasur Azimov',
        shortName: 'Dr. Azimov',
        title: 'Bosh shifokor • Implantolog',
        email: 'j.azimov@dentuz.uz',
        password: 'Password123!',
        role: 'owner',
        phone: '+998 90 123 45 67',
        avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150',
        clinicId: clinic.id,
      },
      {
        name: 'Dr. Malika Saidova',
        shortName: 'Dr. Saidova',
        title: 'Ortodont',
        email: 'm.saidova@dentuz.uz',
        password: 'Password123!',
        role: 'doctor',
        phone: '+998 93 319 44 28',
        avatarUrl: 'https://images.unsplash.com/photo-1594824813576-2f085731f822?w=150',
        clinicId: clinic.id,
      },
      {
        name: 'Dr. Jamshid Karimov',
        shortName: 'Dr. Karimov',
        title: 'Terapevt-Stomatolog',
        email: 'j.karimov@dentuz.uz',
        password: 'Password123!',
        role: 'doctor',
        phone: '+998 97 711 09 85',
        avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150',
        clinicId: clinic.id,
      },
      {
        name: 'Nilufar Rahimova',
        shortName: 'N. Rahimova',
        title: 'Bosh assistent • Hamshira',
        email: 'n.rahimova@dentuz.uz',
        password: 'Password123!',
        role: 'nurse',
        phone: '+998 91 445 22 19',
        clinicId: clinic.id,
      },
      {
        name: 'Bobur Mirzayev',
        shortName: 'B. Mirzayev',
        title: 'Administrator / Qabulxona',
        email: 'admin@dentuz.uz',
        password: 'Password123!',
        role: 'receptionist',
        phone: '+998 99 800 11 22',
        clinicId: clinic.id,
      },
    ];

    const users = await Promise.all(usersData.map((u) => db.User.create(u)));
    console.log(`✅ ${users.length} ta foydalanuvchi yaratildi (parol: Password123!)`);

    // 3. Shifokorlar profili
    const doctors = await Promise.all([
      db.Doctor.create({
        userId: users[0].id,
        clinicId: clinic.id,
        specialization: 'Bosh shifokor • Implantolog',
        cabinetNumber: 1,
        workingHours: '09:00-18:00',
      }),
      db.Doctor.create({
        userId: users[1].id,
        clinicId: clinic.id,
        specialization: 'Ortodont',
        cabinetNumber: 2,
        workingHours: '09:00-17:00',
      }),
      db.Doctor.create({
        userId: users[2].id,
        clinicId: clinic.id,
        specialization: 'Terapevt-Stomatolog',
        cabinetNumber: 3,
        workingHours: '10:00-19:00',
      }),
    ]);
    console.log(`✅ ${doctors.length} ta shifokor profili yaratildi`);

    // 4. Bemorlar (Patients) - 32 ta to'liq real bemorlar
    const patientsData = [
      {
        id: 'P-1042',
        name: 'Anvar Qosimov',
        phone: '+998 90 842 11 00',
        birthdate: '1989-08-14',
        age: 35,
        lastVisit: '2026-09-18',
        lastProcedure: 'Karies davolash',
        nextVisit: 'Bugun • 09:00',
        status: 'today',
        allergies: 'Penitsillin',
        notes: 'Doimiy bemor, og\'riq sezuvchanligi past',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1043',
        name: 'Malika Saidova',
        phone: '+998 93 319 44 28',
        birthdate: '1995-11-22',
        age: 29,
        lastVisit: '2026-09-15',
        lastProcedure: 'Breket korreksiyasi',
        nextVisit: 'Bugun • 10:15',
        status: 'today',
        allergies: 'Yo\'q',
        notes: 'Elastik tortqichlar almashtirildi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1044',
        name: 'Jamshid Karimov',
        phone: '+998 97 711 09 85',
        birthdate: '1982-04-03',
        age: 43,
        lastVisit: '2026-09-10',
        lastProcedure: 'Tish tozalash',
        nextVisit: 'Bugun • 11:30',
        status: 'today',
        allergies: 'Lidokain (ehtiyotkorlik)',
        notes: 'Profilaktik tozalash har 6 oyda',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1045',
        name: 'Nilufar Rahimova',
        phone: '+998 91 445 22 19',
        birthdate: '1991-06-19',
        age: 33,
        lastVisit: '2026-09-22',
        lastProcedure: 'Tish oqartirish',
        nextVisit: 'Bugun • 14:00',
        status: 'today',
        allergies: 'Yo\'q',
        notes: 'Zoom 4 kursi o\'tkazildi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1046',
        name: 'Farrux Zokirov',
        phone: '+998 90 912 34 56',
        birthdate: '1976-12-08',
        age: 48,
        lastVisit: '2026-09-15',
        lastProcedure: 'Implantatsiya',
        nextVisit: '30-Sentabr • 15:00',
        status: 'debtor',
        allergies: 'Yo\'q',
        notes: 'Ikkinchi bosqich to\'lovi qolgan',
        balance: -1800000,
        clinicId: clinic.id,
      },
      {
        id: 'P-1047',
        name: 'Shahlo Umarova',
        phone: '+998 94 654 32 10',
        birthdate: '1998-02-27',
        age: 26,
        lastVisit: '2026-09-12',
        lastProcedure: 'Retinirlangan tish olish',
        nextVisit: '26-Sentabr • 14:00',
        status: 'scheduled',
        allergies: 'Aspirin',
        notes: 'Tiklanish davri nazoratda',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1048',
        name: 'Otabek Soliyev',
        phone: '+998 94 650 33 22',
        birthdate: '1985-12-08',
        age: 39,
        lastVisit: '2026-09-19',
        lastProcedure: 'Plomba almashtirish',
        nextVisit: '28-Sentabr • 10:00',
        status: 'scheduled',
        allergies: 'Yo\'q',
        notes: '#36 tish plomba qo\'yildi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1049',
        name: 'Sardor Rashidov',
        phone: '+998 90 333 44 55',
        birthdate: '1990-07-05',
        age: 34,
        lastVisit: '2026-09-14',
        lastProcedure: 'Endodontik davolash',
        nextVisit: '02-Oktabr • 12:00',
        status: 'debtor',
        allergies: 'Yo\'q',
        notes: '#16 tish kanallari davolandi, qarz qolgan',
        balance: -850000,
        clinicId: clinic.id,
      },
      {
        id: 'P-1050',
        name: 'Dildora Azimova',
        phone: '+998 93 421 55 66',
        birthdate: '1994-03-17',
        age: 30,
        lastVisit: '2026-09-16',
        lastProcedure: 'Vinir konsultatsiyasi',
        nextVisit: '04-Oktabr • 11:00',
        status: 'scheduled',
        allergies: 'Lateks',
        notes: '6 ta oldingi tishga E-max vinirlar rejalashtirildi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1051',
        name: 'Rustam Xoliqov',
        phone: '+998 90 777 88 99',
        birthdate: '1983-05-12',
        age: 41,
        lastVisit: '2026-09-11',
        lastProcedure: 'Metallokeramika toj',
        nextVisit: '05-Oktabr • 14:30',
        status: 'debtor',
        allergies: 'Yo\'q',
        notes: '#25 va #26 tishlarga metallokeramika toj o\'rnatish',
        balance: -1200000,
        clinicId: clinic.id,
      },
      {
        id: 'P-1052',
        name: 'Kamola Tursunova',
        phone: '+998 91 334 12 78',
        birthdate: '1997-09-25',
        age: 27,
        lastVisit: '2026-09-20',
        lastProcedure: 'Tish toshini tozalash',
        nextVisit: 'Bugun • 15:00',
        status: 'today',
        allergies: 'Yo\'q',
        notes: 'Profilaktik tekshiruv va tozalash',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1053',
        name: 'Bekzod Ahmedov',
        phone: '+998 99 555 44 33',
        birthdate: '2001-11-04',
        age: 23,
        lastVisit: '2026-09-08',
        lastProcedure: 'Breket konsultatsiyasi',
        nextVisit: '06-Oktabr • 16:00',
        status: 'scheduled',
        allergies: 'Yo\'q',
        notes: 'Rentgen tahlili o\'tkazildi, breket o\'rnatiladi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1054',
        name: 'Gulnoza Ismoilova',
        phone: '+998 97 400 11 22',
        birthdate: '1988-01-30',
        age: 36,
        lastVisit: '2026-09-17',
        lastProcedure: 'Flyuorizatsiya',
        nextVisit: null,
        status: 'all',
        allergies: 'Yo\'q',
        notes: 'Emal mustahkamlandi, 6 oydan keyin nazorat',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1055',
        name: 'Shavkat Mirzayev',
        phone: '+998 90 112 33 44',
        birthdate: '1973-04-19',
        age: 51,
        lastVisit: '2026-09-13',
        lastProcedure: '2 ta implant o\'rnatish',
        nextVisit: '08-Oktabr • 10:00',
        status: 'debtor',
        allergies: 'Yo\'q',
        notes: '#46 va #47 sohasiga implantatsiya, qarz qolgan',
        balance: -4500000,
        clinicId: clinic.id,
      },
      {
        id: 'P-1056',
        name: 'Zilola Nazarova',
        phone: '+998 94 220 99 88',
        birthdate: '1993-08-11',
        age: 31,
        lastVisit: '2026-09-14',
        lastProcedure: 'Tish kanallarini qayta tozalash',
        nextVisit: '07-Oktabr • 15:00',
        status: 'scheduled',
        allergies: 'Penitsillin',
        notes: 'Antiseptik dorili bog\'lam qo\'yildi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1057',
        name: 'Azizbek Yusupov',
        phone: '+998 93 888 77 66',
        birthdate: '1986-12-03',
        age: 38,
        lastVisit: '2026-09-21',
        lastProcedure: 'Rentgen va ko\'rik',
        nextVisit: null,
        status: 'all',
        allergies: 'Yo\'q',
        notes: 'Sog\'lom holat, muolaja talab qilinmadi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1058',
        name: 'Madina Sobirova',
        phone: '+998 91 700 80 90',
        birthdate: '1996-06-15',
        age: 28,
        lastVisit: '2026-09-19',
        lastProcedure: 'Estetik restavratsiya',
        nextVisit: 'Bugun • 16:15',
        status: 'today',
        allergies: 'Yo\'q',
        notes: '#11 va #21 tishlar shakli qayta tiklandi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1059',
        name: 'Jasur Qodirov',
        phone: '+998 90 456 78 90',
        birthdate: '1984-10-28',
        age: 40,
        lastVisit: '2026-09-12',
        lastProcedure: 'Keramika inley qo\'yish',
        nextVisit: '10-Oktabr • 11:00',
        status: 'debtor',
        allergies: 'Yo\'q',
        notes: 'Inley tayyor bo\'lishi kutilmoqda',
        balance: -650000,
        clinicId: clinic.id,
      },
      {
        id: 'P-1060',
        name: 'Umida Ergasheva',
        phone: '+998 97 999 11 00',
        birthdate: '1992-02-14',
        age: 32,
        lastVisit: '2026-09-15',
        lastProcedure: 'Gingivit davolash',
        nextVisit: '09-Oktabr • 11:30',
        status: 'scheduled',
        allergies: 'Yo\'q',
        notes: 'Dori vositalari bilan milklar chayildi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1061',
        name: 'Sherzod Murodov',
        phone: '+998 99 123 45 67',
        birthdate: '1979-07-22',
        age: 45,
        lastVisit: '2026-09-10',
        lastProcedure: 'Aql tishi operatsiyasi',
        nextVisit: '11-Oktabr • 12:00',
        status: 'debtor',
        allergies: 'Yo\'q',
        notes: '#38 tish olingan, tikuvlar olingandan so\'ng yakuniy to\'lov',
        balance: -950000,
        clinicId: clinic.id,
      },
      {
        id: 'P-1062',
        name: 'Lola Abdullayeva',
        phone: '+998 93 234 56 78',
        birthdate: '2000-05-18',
        age: 24,
        lastVisit: '2026-09-22',
        lastProcedure: 'Bolalar tish profilaktikasi',
        nextVisit: null,
        status: 'all',
        allergies: 'Yo\'q',
        notes: 'Silant bilan fissuralar berkitildi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1063',
        name: 'Muzaffar G\'ofurov',
        phone: '+998 90 654 98 71',
        birthdate: '1987-09-09',
        age: 37,
        lastVisit: '2026-09-18',
        lastProcedure: 'Tsirkoniy koronka',
        nextVisit: '10-Oktabr • 10:30',
        status: 'scheduled',
        allergies: 'Yo\'q',
        notes: 'Izlar olindi, laboratoriyaga topshirildi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1064',
        name: 'Hilola Rahimova',
        phone: '+998 91 111 22 33',
        birthdate: '1999-12-01',
        age: 25,
        lastVisit: '2026-09-21',
        lastProcedure: 'Tish sezuvchanligini pasaytirish',
        nextVisit: 'Bugun • 17:00',
        status: 'today',
        allergies: 'Yo\'q',
        notes: 'Desensitayzer qo\'llanildi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1065',
        name: 'Olimjon Mahmudov',
        phone: '+998 94 333 22 11',
        birthdate: '1971-03-14',
        age: 53,
        lastVisit: '2026-09-13',
        lastProcedure: 'Sinus-lifting va implant',
        nextVisit: '12-Oktabr • 14:00',
        status: 'debtor',
        allergies: 'Yo\'q',
        notes: 'Yuqori jag\' sinus-lifting o\'tkazildi',
        balance: -3200000,
        clinicId: clinic.id,
      },
      {
        id: 'P-1066',
        name: 'Nargiza Sharipova',
        phone: '+998 97 888 99 00',
        birthdate: '1995-04-20',
        age: 29,
        lastVisit: '2026-09-17',
        lastProcedure: 'Ortodontik retainer',
        nextVisit: '11-Oktabr • 14:00',
        status: 'scheduled',
        allergies: 'Yo\'q',
        notes: 'Breket yechildi, retainer tekshiruvi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1067',
        name: 'Bobur Alimov',
        phone: '+998 90 222 11 00',
        birthdate: '1981-08-08',
        age: 43,
        lastVisit: '2026-09-19',
        lastProcedure: 'Tish toshini tozalash',
        nextVisit: null,
        status: 'all',
        allergies: 'Yo\'q',
        notes: 'Tish gigiyenasi qoniqarli',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1068',
        name: 'Shahnoza Jalilova',
        phone: '+998 93 123 00 99',
        birthdate: '1998-10-10',
        age: 26,
        lastVisit: '2026-09-22',
        lastProcedure: 'Karies profilaktikasi',
        nextVisit: 'Bugun • 18:00',
        status: 'today',
        allergies: 'Yo\'q',
        notes: '#15 tish plomba qo\'yildi',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1069',
        name: 'Davron Toirov',
        phone: '+998 99 876 54 32',
        birthdate: '1968-11-29',
        age: 56,
        lastVisit: '2026-09-14',
        lastProcedure: 'Byugel protez tayyorlash',
        nextVisit: '13-Oktabr • 11:00',
        status: 'debtor',
        allergies: 'Yo\'q',
        notes: 'Protez sinovi o\'tkazildi',
        balance: -2100000,
        clinicId: clinic.id,
      },
      {
        id: 'P-1070',
        name: 'Mohira Yoqubova',
        phone: '+998 91 555 66 77',
        birthdate: '1994-07-07',
        age: 30,
        lastVisit: '2026-09-16',
        lastProcedure: 'Kompozit vinir',
        nextVisit: '12-Oktabr • 15:30',
        status: 'scheduled',
        allergies: 'Yo\'q',
        notes: 'Frontal sohada restavratsiya',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1071',
        name: 'Nodirbek Boboyev',
        phone: '+998 90 900 80 70',
        birthdate: '1985-02-17',
        age: 39,
        lastVisit: '2026-09-20',
        lastProcedure: 'Profilaktik ko\'rik',
        nextVisit: null,
        status: 'all',
        allergies: 'Yo\'q',
        notes: 'Shikoyatlar yo\'q',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1072',
        name: 'Sevara Karimova',
        phone: '+998 94 777 66 55',
        birthdate: '2002-09-03',
        age: 22,
        lastVisit: '2026-09-15',
        lastProcedure: 'Damon Clear breket',
        nextVisit: '14-Oktabr • 09:30',
        status: 'scheduled',
        allergies: 'Yo\'q',
        notes: 'Shaffof keramik breket o\'rnatilgan',
        balance: 0,
        clinicId: clinic.id,
      },
      {
        id: 'P-1073',
        name: 'Ilhom Vohidov',
        phone: '+998 97 101 20 30',
        birthdate: '1975-06-24',
        age: 49,
        lastVisit: '2026-09-11',
        lastProcedure: 'Endodontik mikro-jarrohlik',
        nextVisit: '15-Oktabr • 16:00',
        status: 'debtor',
        allergies: 'Yo\'q',
        notes: 'Ildiz uchi rezektsiyasi o\'tkazildi',
        balance: -1400000,
        clinicId: clinic.id,
      },
    ];

    // 4.1 Qo'shimcha 370 ta to'liq real bemorlar generatsiyasi (Jami 400+ ta bemor)
    const maleFirstNames = ['Aziz', 'Bekzod', 'Diyor', 'Jasur', 'Nodir', 'Olim', 'Rustam', 'Sanjar', 'Farrux', 'Shavkat', 'Sherzod', 'Muzaffar', 'Bobur', 'Otabek', 'Sardor', 'Javohir', 'Shohruh', 'Elyor', 'Doniyor', 'Alisher', 'Temur', 'Eldor', 'Abbos', 'Anvar', 'Davron', 'Jahongir', 'Xurshid', 'Umid', 'Ilhom', 'Akmal'];
    const femaleFirstNames = ['Gulnoza', 'Lola', 'Madina', 'Umida', 'Hilola', 'Zilola', 'Kamola', 'Nilufar', 'Shahlo', 'Shahnoza', 'Dildora', 'Nargiza', 'Mohira', 'Sevara', 'Feruza', 'Dilfuza', 'Nigora', 'Rayhon', 'Ziyoda', 'Yulduz', 'Nozima', 'Munisa', 'Go\'zal', 'Zarnigor', 'Sabina', 'Malika', 'Zulayho', 'Ozoda'];
    const lastNamesRoots = ['Karim', 'Azim', 'Tursun', 'Ahmed', 'Yusup', 'Sobir', 'Nazar', 'Ismoil', 'Abdullay', 'Murod', 'Rahim', 'Qodir', 'Xoliq', 'Ergash', 'G\'ofur', 'Aliy', 'Said', 'Umar', 'Soliy', 'Rashid', 'Mahmud', 'Sharip', 'Jalil', 'Toir', 'Yoqub', 'Boboy', 'Vohid', 'Mirzay', 'Normat', 'Jo\'ray'];
    const extraProcedures = [
      'Karies davolash va kompozit plomba', 'Tish tozalash (Air-Flow)', 'Endodontik davolash',
      'Metallokeramika toj o\'rnatish', 'Tsirkoniy koronka', 'Damon Q breket korreksiyasi',
      'Straumann implantatsiyasi', 'Tish oqartirish (Zoom 4)', 'Aql tishini jarrohlik yo\'li bilan olish',
      'E-max vinirlar konsultatsiyasi', 'Bolalar tish profilaktikasi', 'Sinus-lifting va suyak plastikasi'
    ];

    for (let i = 1; i <= 370; i++) {
      const isMale = i % 2 === 0;
      const fn = isMale ? maleFirstNames[i % maleFirstNames.length] : femaleFirstNames[i % femaleFirstNames.length];
      const rootLn = lastNamesRoots[(i + Math.floor(i / maleFirstNames.length)) % lastNamesRoots.length];
      const ln = isMale ? `${rootLn}ov` : `${rootLn}ova`;
      const pId = `P-${1073 + i}`;
      const proc = extraProcedures[i % extraProcedures.length];
      const statusMod = i % 10;
      let status = 'all';
      let balance = 0;
      let nextVisit = null;

      if (statusMod === 0 || statusMod === 5) {
        status = 'today';
        nextVisit = `Bugun • ${10 + (i % 8)}:00`;
      } else if (statusMod === 2 || statusMod === 7) {
        status = 'debtor';
        balance = -((i * 150000) % 2500000 + 200000);
        nextVisit = `${((i % 25) + 1)}-Oktabr • 14:00`;
      } else if (statusMod % 2 === 0) {
        status = 'scheduled';
        nextVisit = `${((i % 28) + 1)}-Oktabr • ${9 + (i % 9)}:30`;
      }

      const birthYear = 1965 + (i % 40);
      const birthMonth = ((i % 12) + 1).toString().padStart(2, '0');
      const birthDay = ((i % 28) + 1).toString().padStart(2, '0');
      const pfx = ['90', '91', '93', '94', '95', '97', '98', '99', '88', '77', '33'][i % 11];
      const phone = `+998 ${pfx} ${Math.floor(100 + Math.random() * 899)} ${Math.floor(10 + Math.random() * 89)} ${Math.floor(10 + Math.random() * 89)}`;

      patientsData.push({
        id: pId,
        name: `${fn} ${ln}`,
        phone,
        birthdate: `${birthYear}-${birthMonth}-${birthDay}`,
        age: 2026 - birthYear,
        lastVisit: `2026-09-${((i % 20) + 1).toString().padStart(2, '0')}`,
        lastProcedure: proc,
        nextVisit,
        status,
        allergies: i % 8 === 0 ? 'Penitsillin' : (i % 15 === 0 ? 'Lidokain' : 'Yo\'q'),
        notes: 'Klinik karta faol, elektron tarix yuritilmoqda',
        balance,
        clinicId: clinic.id
      });
    }

    const patients = await db.Patient.bulkCreate(patientsData);
    console.log(`✅ ${patients.length} ta bemor yaratildi`);

    // 5. Qabullar (Appointments)
    const today = new Date().toISOString().split('T')[0];
    const appointmentsData = [
      {
        id: 'apt-1',
        time: '09:00',
        duration: 45,
        patientId: patients[0].id,
        patientName: patients[0].name,
        procedure: 'Karies davolash',
        doctorId: doctors[0].id,
        doctorSlug: 'azimov',
        doctorName: 'Dr. Jasur Azimov',
        status: 'in_progress',
        day: 'mon',
        date: today,
        chair: 1,
        color: 'emerald',
        clinicId: clinic.id,
      },
      {
        id: 'apt-2',
        time: '10:15',
        duration: 60,
        patientId: patients[1].id,
        patientName: patients[1].name,
        procedure: 'Breket korreksiyasi',
        doctorId: doctors[1].id,
        doctorSlug: 'saidova',
        doctorName: 'Dr. Malika Saidova',
        status: 'pending',
        day: 'mon',
        date: today,
        chair: 2,
        color: 'cyan',
        clinicId: clinic.id,
      },
      {
        id: 'apt-3',
        time: '11:30',
        duration: 45,
        patientId: patients[2].id,
        patientName: patients[2].name,
        procedure: 'Tish tozalash',
        doctorId: doctors[2].id,
        doctorSlug: 'karimov',
        doctorName: 'Dr. Jamshid Karimov',
        status: 'pending',
        day: 'mon',
        date: today,
        chair: 3,
        color: 'amber',
        clinicId: clinic.id,
      },
      {
        id: 'apt-4',
        time: '14:00',
        duration: 45,
        patientId: patients[3].id,
        patientName: patients[3].name,
        procedure: 'Tish oqartirish',
        doctorId: doctors[0].id,
        doctorSlug: 'azimov',
        doctorName: 'Dr. Jasur Azimov',
        status: 'pending',
        day: 'mon',
        date: today,
        chair: 1,
        color: 'emerald',
        clinicId: clinic.id,
      },
      {
        id: 'apt-5',
        time: '15:00',
        duration: 45,
        patientId: patients[10].id,
        patientName: patients[10].name,
        procedure: 'Tish toshini tozalash',
        doctorId: doctors[2].id,
        doctorSlug: 'karimov',
        doctorName: 'Dr. Jamshid Karimov',
        status: 'pending',
        day: 'mon',
        date: today,
        chair: 3,
        color: 'amber',
        clinicId: clinic.id,
      },
      {
        id: 'apt-6',
        time: '16:15',
        duration: 45,
        patientId: patients[16].id,
        patientName: patients[16].name,
        procedure: 'Estetik restavratsiya',
        doctorId: doctors[1].id,
        doctorSlug: 'saidova',
        doctorName: 'Dr. Malika Saidova',
        status: 'pending',
        day: 'mon',
        date: today,
        chair: 2,
        color: 'cyan',
        clinicId: clinic.id,
      },
      {
        id: 'apt-7',
        time: '17:00',
        duration: 30,
        patientId: patients[22].id,
        patientName: patients[22].name,
        procedure: 'Tish sezuvchanligini pasaytirish',
        doctorId: doctors[2].id,
        doctorSlug: 'karimov',
        doctorName: 'Dr. Jamshid Karimov',
        status: 'pending',
        day: 'mon',
        date: today,
        chair: 3,
        color: 'amber',
        clinicId: clinic.id,
      },
      {
        id: 'apt-8',
        time: '18:00',
        duration: 45,
        patientId: patients[26].id,
        patientName: patients[26].name,
        procedure: 'Karies profilaktikasi',
        doctorId: doctors[0].id,
        doctorSlug: 'azimov',
        doctorName: 'Dr. Jasur Azimov',
        status: 'pending',
        day: 'mon',
        date: today,
        chair: 1,
        color: 'emerald',
        clinicId: clinic.id,
      },
      {
        id: 'apt-9',
        time: '14:00',
        duration: 45,
        patientId: patients[5].id,
        patientName: patients[5].name,
        procedure: 'Retinirlangan tish olish',
        doctorId: doctors[0].id,
        doctorSlug: 'azimov',
        doctorName: 'Dr. Jasur Azimov',
        status: 'pending',
        day: 'sat',
        date: '2026-09-26',
        chair: 1,
        color: 'emerald',
        clinicId: clinic.id,
      },
      {
        id: 'apt-10',
        time: '10:00',
        duration: 30,
        patientId: patients[6].id,
        patientName: patients[6].name,
        procedure: 'Plomba almashtirish',
        doctorId: doctors[2].id,
        doctorSlug: 'karimov',
        doctorName: 'Dr. Jamshid Karimov',
        status: 'pending',
        day: 'mon',
        date: '2026-09-28',
        chair: 3,
        color: 'amber',
        clinicId: clinic.id,
      },
      {
        id: 'apt-11',
        time: '15:00',
        duration: 60,
        patientId: patients[4].id,
        patientName: patients[4].name,
        procedure: 'Implantatsiya',
        doctorId: doctors[0].id,
        doctorSlug: 'azimov',
        doctorName: 'Dr. Jasur Azimov',
        status: 'pending',
        day: 'wed',
        date: '2026-09-30',
        chair: 1,
        color: 'emerald',
        clinicId: clinic.id,
      },
    ];

    const appointments = await Promise.all(appointmentsData.map((a) => db.Appointment.create(a)));
    console.log(`✅ ${appointments.length} ta qabul yaratildi`);

    // 6. Xizmatlar preyskuranti (Services)
    const servicesData = [
      {
        name: 'Tish plombalash (Fotopolimer)',
        category: 'therapy',
        code: 'TH-01',
        price: 250000,
        duration: 45,
        description: 'Kariesni tozalash va fotopolimer kompozit plomba',
        isActive: true,
        clinicId: clinic.id,
      },
      {
        name: 'Professional gigiyenik tozalash (Air-Flow)',
        category: 'hygiene',
        code: 'HY-01',
        price: 350000,
        duration: 60,
        description: 'Tish toshlari va dog\'larni ultratovush orqali tozalash',
        isActive: true,
        clinicId: clinic.id,
      },
      {
        name: 'Tish implantatsiyasi (Osstem, Koreya)',
        category: 'surgery',
        code: 'SG-01',
        price: 3500000,
        duration: 90,
        description: 'Titanium implant va dastlabki suyak integratsiyasi',
        isActive: true,
        clinicId: clinic.id,
      },
      {
        name: 'Metall breket tizimi (ikkala jag\')',
        category: 'orthodontics',
        code: 'OR-01',
        price: 6000000,
        duration: 120,
        description: 'Klassik metall breketlar va o\'rnatish',
        isActive: true,
        clinicId: clinic.id,
      },
    ];
    await Promise.all(servicesData.map((s) => db.Service.create(s)));
    console.log(`✅ ${servicesData.length} ta xizmat yaratildi`);

    // 7. Ombor mollari (Inventory)
    const inventoryData = [
      {
        name: 'Septanest 1:100000 (Anesteziya)',
        category: 'medication',
        sku: 'MED-SEPT-01',
        unit: 'quti',
        quantity: 35,
        minQuantity: 10,
        costPrice: 180000,
        supplier: 'DentMarket Tashkent',
        expiryDate: '2027-12-31',
        clinicId: clinic.id,
      },
      {
        name: 'Filtek Z250 Universal Kompozit Plomba',
        category: 'consumable',
        sku: 'CON-FILT-01',
        unit: 'dona',
        quantity: 18,
        minQuantity: 5,
        costPrice: 220000,
        supplier: 'Dental Trade LLC',
        expiryDate: '2026-11-30',
        clinicId: clinic.id,
      },
      {
        name: 'Osstem TS III SA Implant (4.0 x 10mm)',
        category: 'implant',
        sku: 'IMP-OSST-01',
        unit: 'dona',
        quantity: 12,
        minQuantity: 3,
        costPrice: 1200000,
        supplier: 'Osstem Uzbekistan',
        expiryDate: '2029-06-30',
        clinicId: clinic.id,
      },
    ];
    await Promise.all(inventoryData.map((inv) => db.Inventory.create(inv)));
    console.log(`✅ ${inventoryData.length} ta ombor mahsuloti yaratildi`);

    // 8. Hisob-fakturalar (Invoices)
    const invoicesData = [
      {
        id: 'INV-2026-001',
        patientId: patients[0].id,
        patient: patients[0].name,
        doctor: 'Dr. Jasur Azimov',
        procedure: 'Karies davolash',
        date: today,
        method: 'Payme',
        amount: 250000,
        status: 'paid',
        clinicId: clinic.id,
      },
      {
        id: 'INV-2026-002',
        patientId: patients[1].id,
        patient: patients[1].name,
        doctor: 'Dr. Malika Saidova',
        procedure: 'Breket korreksiyasi',
        date: today,
        method: 'Click',
        amount: 300000,
        status: 'paid',
        clinicId: clinic.id,
      },
      {
        id: 'INV-2026-003',
        patientId: patients[4].id,
        patient: patients[4].name,
        doctor: 'Dr. Jasur Azimov',
        procedure: 'Implantatsiya',
        date: today,
        method: 'Naqd',
        amount: 3500000,
        status: 'partial',
        clinicId: clinic.id,
      },
      {
        id: 'INV-2026-004',
        patientId: patients[3].id,
        patient: patients[3].name,
        doctor: 'Dr. Jasur Azimov',
        procedure: 'Tish oqartirish',
        date: today,
        method: 'Uzcard',
        amount: 600000,
        status: 'paid',
        clinicId: clinic.id,
      },
      {
        id: 'INV-2026-005',
        patientId: patients[7].id,
        patient: patients[7].name,
        doctor: 'Dr. Jamshid Karimov',
        procedure: 'Endodontik davolash',
        date: today,
        method: 'Naqd',
        amount: 850000,
        status: 'pending',
        clinicId: clinic.id,
      },
      {
        id: 'INV-2026-006',
        patientId: patients[9].id,
        patient: patients[9].name,
        doctor: 'Dr. Jasur Azimov',
        procedure: 'Metallokeramika toj',
        date: today,
        method: 'Humo',
        amount: 1200000,
        status: 'pending',
        clinicId: clinic.id,
      },
      {
        id: 'INV-2026-007',
        patientId: patients[10].id,
        patient: patients[10].name,
        doctor: 'Dr. Jamshid Karimov',
        procedure: 'Tish toshini tozalash',
        date: today,
        method: 'Payme',
        amount: 350000,
        status: 'paid',
        clinicId: clinic.id,
      },
      {
        id: 'INV-2026-008',
        patientId: patients[13].id,
        patient: patients[13].name,
        doctor: 'Dr. Jasur Azimov',
        procedure: '2 ta implant o\'rnatish',
        date: today,
        method: 'Naqd',
        amount: 4500000,
        status: 'partial',
        clinicId: clinic.id,
      },
      {
        id: 'INV-2026-009',
        patientId: patients[16].id,
        patient: patients[16].name,
        doctor: 'Dr. Malika Saidova',
        procedure: 'Estetik restavratsiya',
        date: today,
        method: 'Click',
        amount: 550000,
        status: 'paid',
        clinicId: clinic.id,
      },
      {
        id: 'INV-2026-010',
        patientId: patients[17].id,
        patient: patients[17].name,
        doctor: 'Dr. Jamshid Karimov',
        procedure: 'Keramika inley',
        date: today,
        method: 'Uzcard',
        amount: 650000,
        status: 'pending',
        clinicId: clinic.id,
      },
      {
        id: 'INV-2026-011',
        patientId: patients[19].id,
        patient: patients[19].name,
        doctor: 'Dr. Jasur Azimov',
        procedure: 'Aql tishi operatsiyasi',
        date: today,
        method: 'Naqd',
        amount: 950000,
        status: 'pending',
        clinicId: clinic.id,
      },
      {
        id: 'INV-2026-012',
        patientId: patients[23].id,
        patient: patients[23].name,
        doctor: 'Dr. Jasur Azimov',
        procedure: 'Sinus-lifting va implant',
        date: today,
        method: 'Humo',
        amount: 3200000,
        status: 'pending',
        clinicId: clinic.id,
      },
    ];
    await Promise.all(invoicesData.map((inv) => db.Invoice.create(inv)));
    console.log(`✅ ${invoicesData.length} ta hisob-faktura yaratildi`);

    // 9. Odontogramma
    await db.Odontogram.create({
      patientId: patients[0].id,
      teeth: {
        '16': { condition: 'caries', notes: 'Okluzal karies' },
        '11': { condition: 'healthy', notes: '' },
        '21': { condition: 'healthy', notes: '' },
        '26': { condition: 'filled', notes: 'Fotopolimer plomba' },
        '36': { condition: 'missing', notes: 'Olingan tish' },
        '46': { condition: 'crown', notes: 'Tsirkoniy toji' },
      },
      lastUpdatedBy: users[0].id,
    });
    console.log(`✅ Odontogramma yaratildi bemor uchun: ${patients[0].name}`);

    console.log('\n🎉 Seed muvaffaqiyatli yakunlandi!');
    console.log('-------------------------------------------');
    console.log('Klinika: DentUz Markaziy Klinika');
    console.log('Login: j.azimov@dentuz.uz (Owner)');
    console.log('Login: m.saidova@dentuz.uz (Doctor)');
    console.log('Login: admin@dentuz.uz (Receptionist)');
    console.log('Parol: Password123!');
    console.log('-------------------------------------------');

    process.exit(0);
  } catch (error) {
    console.error('❌ Seed xatosi:', error);
    process.exit(1);
  }
};

seed();
